# Character mappings for each language

HINDI_CHAR_MAP = {
    'character_10_yna': 'ज्ञ',
    'character_11_taamatar': 'ा',
    'character_12_thaa': 'था',
    'character_13_daa': 'डा',
    'character_14_dhaa': 'ढा',
    'character_15_dda': 'द',
    'character_1_aa': 'आ',
    'character_2_i': 'इ',
    'character_3_ii': 'ई',
    'character_4_u': 'उ',
    'character_5_uu': 'ऊ',
    'character_6_ri': 'ऋ',
    'character_7_e': 'ए',
    'character_8_ai': 'ऐ',
    'character_9_o': 'ओ',
}

MALAYALAM_CHAR_MAP = {
    'CHAR1': 'അ',
    'CHAR2': 'ആ',
    'CHAR3': 'ഇ',
    'CHAR4': 'ഈ',
    'CHAR5': 'ഉ',
    'CHAR6': 'ഊ',
    'CHAR7': 'ഋ',
    'CHAR8': 'ഌ',
    'CHAR9': 'എ',
    'CHAR10': 'ഏ',
    'CHAR11': 'ഐ',
    'CHAR12': 'ഒ',
    'CHAR13': 'ഓ',
    'CHAR14': 'ഔ',
    'CHAR15': 'ക',
    'CHAR16': 'ഖ',
    'CHAR17': 'ഗ',
    'CHAR18': 'ഘ',
}

TAMIL_CHAR_MAP = {
    '1': 'அ',
    '2': 'ஆ',
    '3': 'இ',
    '4': 'ஈ',
    '5': 'உ',
    '6': 'ஊ',
    '7': 'எ',
    '8': 'ஏ',
    '9': 'ஐ',
    '10': 'ஒ',
    '11': 'ஓ',
    '12': 'ஔ',
    '13': 'க',
    '14': 'கா',
    '15': 'கி',
    '16': 'கீ',
    '17': 'கு',
    '18': 'கூ',
}
